### ISSUE TITLE
ini_set value typehint

### ISSUE THREAD

**Issue by Kharhamel** [thecodingmachine/safe#133]
The function ini_set generated has its second parameter typehinted as string, but the documentation says it can be string|int|float|bool.

No typehint should be generated since we already have a correct @param annotation

**Comment by Kharhamel** [comment]
#134

**Comment by Kharhamel** [comment]
done in 1.0.0-beta1

**Comment by daltones** [comment]
Hi @Kharhamel 

It looks like this still an issue in v3.1.1. See [`Safe\ini_set()` declaration for PHP 8.4](https://github.com/thecodingmachine/safe/blob/234f6fe34a0bead8c5ae1cfc0800539442e6f619/generated/8.4/info.php#L430).

Reference: https://www.php.net/manual/en/function.ini-set.php
